I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 773, in script
    claudia "Sorry about that, kitty. I just wanted to introduce myself, but it looks like my tail beat me to it."
NameError: name 'claudia_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 773, in script
    claudia "Sorry about that, kitty. I just wanted to introduce myself, but it looks like my tail beat me to it."
  File "F:\Users\default.default-PC\Documents\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "F:\Users\default.default-PC\Documents\Renpy\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "F:\Users\default.default-PC\Documents\Renpy\renpy-8.0.3-sdk\renpy\character.py", line 1248, in __call__
    who = renpy.python.py_eval(who)
  File "F:\Users\default.default-PC\Documents\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "F:\Users\default.default-PC\Documents\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'claudia_name' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Requiem of Alice 0.0.2
Sat Mar 18 13:52:05 2023
